[versions]
# plugins
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.2.20-2.0.4"
protobuf = "0.9.6"


#必备
appcompat = "1.7.1"
material = "1.13.0"
#常用库
okhttp = "5.3.2"

retrofit2 = "3.0.0"
fastkv = "3.0.1"
fastjson2 = "2.0.60"
glide = "5.0.5"
base-recyclerview-helper = "4.3.2"

dialogx = "0.0.50"

protobuf-java = "4.33.2"
kotlinx-serialization = "1.9.0"
xphelper = "2.9"

[libraries]

# kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }


#必备
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#常用库
fastkv = { group = 'io.github.billywei01', name = 'fastkv', version.ref = "fastkv" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }
fastjson2-kotlin = { module = "com.alibaba.fastjson2:fastjson2-kotlin", version.ref = "fastjson2" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
base-recyclerview-helper = { module = "io.github.cymchad:BaseRecyclerViewAdapterHelper4", version.ref = "base-recyclerview-helper" }

suzhelan-dialogx = { module = "com.github.suzhelan.DialogX:DialogX", version.ref = "dialogx" }#使用言子楪世改过的dialogx,可以在宿主使用
suzhelan-dialogx-materialstyle = { module = "com.github.suzhelan.DialogX:DialogXMaterialYou", version.ref = "dialogx" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }

#xposed api
xphelper = { module = "com.github.suzhelan:XpHelper", version.ref = "xphelper" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }

#注解扫描器
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "2.2.0" }

byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version = "1.18.3" }

#自定义gradle插件
android-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
